### ISSUE TITLE
Just a note: Encountered issues and corresponding solutions when compiling the project on Windows platform using msvc compiler

### ISSUE THREAD

**Issue by guo-han** [Digital-Humans-23/motion-matching#1]
1. auto convert between std::filesystem::path and std::string is not available, 
    explicit BVHClip/C3DClip(const std::string &filePath) -> explicit BVHClip/C3DClip(const std::filesystem::path &filePath)
    std::string(xxx) -> xxx.string()
    xxx.c_str() -> xxx.string().c_str()
    the modified version is tested to be ok under clang and msvc in linux, mac and windows
3. If use VS code, need to clarify the include folder path in the settings.json

**Comment by eastskykang** [comment]
Thank you for reporting! Have you managed to fix the issue?

**Comment by guo-han** [comment]
Yes, I can solve it. Maybe I can submit a pull request?

**Comment by eastskykang** [comment]
Oh yes that will be great!
